name: device_vendor_info_windows
description: Windows implementation of hardware vendor information in Flutter.
version: 2.0.2
homepage: https://github.com/rk0cc/device_vendor_info
repository: https://github.com/rk0cc/device_vendor_info/tree/main/windows
environment: 
  sdk: ^3.6.0
  flutter: '>=3.27.0'
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  win32_registry: ^1.1.5
  device_vendor_info_interface: ^5.0.1
  async: ^2.11.0
  device_vendor_info_vmchecker: ^1.0.3
dev_dependencies:
  flutter_lints: ^5.0.0
platforms:
  windows:
