name: device_vendor_info
description: Get hardware information (BIOS, Motherboard and System) into Flutter platform.
version: 0.1.0
homepage: https://github.com/rk0cc/device_vendor_info
environment: 
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  device_vendor_info_interface: ^1.0.0+1
  device_vendor_info_unix: ^0.1.0
  device_vendor_info_windows: ^0.1.1
dev_dependencies:
  flutter_lints: ^3.0.1
platforms:
  linux:
  macos:
  windows: 
