name: device_vendor_info_interface
description: Provide standard interface of hardware vendor information in Flutter.
version: 5.0.0
homepage: https://github.com/rk0cc/device_vendor_info
repository: https://github.com/rk0cc/device_vendor_info/tree/main/interface
environment: 
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  json_annotation: ^4.8.1
  intl: '>=0.18.0 <1.0.0'
  async: ^2.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <5.0.0"
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  enough_convert:
    git:
      url: https://github.com/rk0cc/enough_convert.git
      ref: 99b2e6b8477ab2a1af5731501156f2d5a98c4188
platforms:
  linux:
  macos:
  windows: 
