name: device_vendor_info_example
description: "Demo Flutter application for fetching hardware informations"
publish_to: 'none'
version: 2.0.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  device_vendor_info:
    path: ../
  intl: ^0.19.0
  device_vendor_info_vmchecker: ^1.0.0
dev_dependencies:
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
